mybatis-plus:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    database: 0
    host: 47.115.215.176
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.215.176:3306/cms
    username: dgvt
    password: dgvt
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8989

upload:
# 七牛云OSS相关配置
  oss:
    # 配置AK
    accessKey: "pVUsJaZnxy43WwmfyEbDHQFrpMlYq2yV0viHIgFb"
    # 配置SK
    secretKey: "2fysqh6dW5QJDPD4JVHPxo9xEbgy78aIE4G-sWPZ"
    # 配置桶
    bucket: "jiangtang-love"
    # 配置基础域名
    baseUrl: "http://s3hhndr6z.hn-bkt.clouddn.com/"
